language: node_js
node_js:
- '0.10'
branches:
  only:
  - master
install:
- time npm install
- npm list
- git --version
- git describe --tags
- export KBC_REVISION=`git describe --tags`
script: npm run build
sudo: false
cache:
  bundler: true
  directories:
  - node_modules
deploy:
- provider: s3
  access_key_id: AKIAJPIXG5FWMBKORQZA
  secret_access_key:
    secure: YnoCx0iURkQ9H9FLamLh8Hr7n2kosPURs7kYeVc5/AFeaprGSfRjOxP2kkOls9esvNfK3mbMpDStFZc4/BSC5nGG+fOL5WQK8r+YVGzlFXfBNu2FgSC/uGd4QeCOgvEDo7k06320LJrJBqQsUQ5484J7TnDq5AzKljDA77f2+Cc=
  bucket: kbc-uis
  local-dir: dist
  upload-dir: kbc
  acl: public_read
  skip_cleanup: true
  cache_control: max-age=31536000
  detect_encoding: true
  on:
    repo: keboola/kbc-ui
after_deploy:
- echo $KBC_REVISION
- curl -F manifestUrl=https://kbc-uis.s3.amazonaws.com/kbc/$KBC_REVISION/manifest.json -F activate=1
  -H X-Token:$KBC_ADMIN_TOKEN_DEVEL https://martin-connection-devel.keboola.com/admin/manage-apps-api/register
- curl -F manifestUrl=https://kbc-uis.s3.amazonaws.com/kbc/$KBC_REVISION/manifest.json -F activate=1
  -H X-Token:$KBC_ADMIN_TOKEN_PROD https://connection.keboola.com/admin/manage-apps-api/register
notifications:
  slack:
    secure: QEH74o00ud7Q0TjKZ5yWzfHMZyq94KUYR/cWe+P0LbMocCbD25GzW/LnTpM+iJQjkDktR3+iZ53ycLOMbrGzFdPwUDIa98FRjv9nMIz0s1ZQv7/5/ydER7wppYT2ID/paIvUMkFQY0cXq0ZIOii66XwV21FPjVUHbOAxjwyWr+U=
